name: Deploy FastAPI App

on:
  push:
    branches:
      - main  # 메인 브랜치에 푸시될 때 실행

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Deploy to server
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SERVER_SSH_KEY }}
        SERVER_IP: ${{ secrets.SERVER_IP }}
        SERVER_USER: ${{ secrets.SERVER_USER }}
        SERVER_DEPLOY_DIR: ${{ secrets.SERVER_DEPLOY_DIR }}
      run: |
        mkdir -p ~/.ssh/
        echo "$SSH_PRIVATE_KEY" > ~/.ssh/deploy_key
        chmod 600 ~/.ssh/deploy_key
        ssh-keyscan -H $SERVER_IP >> ~/.ssh/known_hosts
        
        scp -i ~/.ssh/deploy_key -r ./* $SERVER_USER@$SERVER_IP:$SERVER_DEPLOY_DIR
        ssh -i ~/.ssh/deploy_key $SERVER_USER@$SERVER_IP "cd $SERVER_DEPLOY_DIR && pip install -r requirements.txt && systemctl restart your_fastapi_service"
