name: Deploy FastAPI App

on:
  push:
    branches:
      - main  # 메인 브랜치에 푸시될 때 실행

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Deploy to server
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SERVER_SSH_KEY }}
        SERVER_IP: ${{ secrets.SERVER_IP }}
        SERVER_USER: ${{ secrets.SERVER_USER }}
        SERVER_DEPLOY_DIR: ${{ secrets.SERVER_DEPLOY_DIR }}
      run: |
        mkdir -p ~/.ssh/
        echo "$SSH_PRIVATE_KEY" > ~/.ssh/deploy_key
        chmod 600 ~/.ssh/deploy_key
        ssh-keyscan -H $SERVER_IP >> ~/.ssh/known_hosts
        
        # 코드를 원격 서버로 복사
        scp -i ~/.ssh/deploy_key -r ./* $SERVER_USER@$SERVER_IP:$SERVER_DEPLOY_DIR
        
        # 원격 서버에서 명령 실행
        ssh -i ~/.ssh/deploy_key $SERVER_USER@$SERVER_IP << EOF
          cd $SERVER_DEPLOY_DIR
          pip install -r requirements.txt
          export AUTH_REDIRECT_URL="https://did-jy.duckdns.org/auth/callback"
          pkill -f "uvicorn main:app"
          nohup uvicorn main:app --host 0.0.0.0 --port 8000 > nohup.out 2>&1 &
          echo "FastAPI application started"
